.rubocop.yml:
  include_todos: true

spec/spec_helper.rb:
  hiera_config: 'spec/fixtures/hiera/hiera.yaml'
  mock_with: ':rspec'

.travis.yml:
  remove_includes:
  - env: PUPPET_GEM_VERSION="~> 4.0" CHECK=parallel_spec
    rvm: 2.1.9
  includes:
  - env: PUPPET_GEM_VERSION="~> 6.0" CHECK=parallel_spec
    rvm: 2.5.1
